# 1 Numpy 操作
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

2.呈上題，將以上數列取出偶數。

3.呈1題，將數列取出3的倍數。

In [73]:
import numpy as np
# 1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
array1=np.arange(0,21)
# 2.呈上題，將以上數列取出偶數。
array2=array1[::2]
# 3.呈1題，將數列取出3的倍數。
array3=array1[3::3]
print("array1=",array1)
print("array2=",array2)
print("array3=",array3)

array1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
array2= [ 0  2  4  6  8 10 12 14 16 18 20]
array3= [ 3  6  9 12 15 18]


# 2  陣列運算及數學

1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")

2.呈上題的array，找出被6除餘1的數的索引

In [74]:
import numpy as np
# 1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。
array1=np.array(range(30))
reshape_array=array1.reshape(5,6,order="F")
print(reshape_array)
# 2.呈上題的array，找出被6除餘1的數的索引
target_index=np.where(reshape_array%6==1)
print(target_index)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]
(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))


# 3
1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?

2.30分貝的聲壓會是50分貝的幾倍?

In [75]:
import numpy as np
# 1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
V1=20000
V0=20
db=20*np.log10(V1/V0)
print(db)
# 2.30分貝的聲壓會是50分貝的幾倍?
V1_30=10**(30/20)*V0
V1_50=10**(50/20)*V0
ratio=V1_30/V1_50
print(ratio)

60.0
0.09999999999999999


# 4 陣列邏輯函數

english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,55,60])

chinese_score = np.array([65,90,82,72,66,77])

上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，運用上列數據回答下列問題。

有多少學生英文成績比數學成績高?

是否全班同學最高分都是國文?

In [76]:
import numpy as np
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,70])
#有多少學生英文成績比數學成績高?
en_greater_math=np.greater(english_score,math_score)
count=np.sum(en_greater_math)
print(count)
#是否全班同學最高分都是國文?
ch_greater_en=np.greater(chinese_score,english_score)
ch_greater_math=np.greater(chinese_score,math_score)
And_compare=np.logical_and(ch_greater_en,ch_greater_math)
result=And_compare.all()
print(And_compare)
print(result)

3
[ True  True  True  True  True False]
False


# 5 統計函數
english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,np.nan,60])

chinese_score = np.array([65,90,82,72,66,77])

上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。

請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

用補考後資料找出與國文成績相關係數最高的學科?


In [77]:
import numpy as np
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])
#請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
avg_score=[np.mean(english_score),np.nanmean(math_score),np.mean(chinese_score)]
max_score=[np.max(english_score),np.nanmax(math_score),np.max(chinese_score)]
min_score=[np.min(english_score),np.nanmin(math_score),np.min(chinese_score)]
std_score=[np.std(english_score),np.nanstd(math_score),np.std(chinese_score)]
print('avg=',np.round(avg_score,3))
print('max=',np.round(max_score,3))
print('min=',np.round(min_score,3))
print('std=',np.round(std_score,3))
print()
#第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score[4]=55
avg_math=np.mean(math_score)
max_math=np.max(math_score)
min_math=np.min(math_score)
std_math=np.std(math_score)
print('avg_math=',np.round(avg_math,3))
print('max_math=',np.round(max_math,3))
print('min_math=',np.round(min_math,3))
print('std_math=',np.round(std_math,3))
print()
#用補考後資料找出與國文成績相關係數最高的學科?
corr_ch_math=np.corrcoef((chinese_score,math_score))[0][1]
corr_ch_en=np.corrcoef((chinese_score,english_score))[0][1]
print("correlation of chinese and math=",np.round(corr_ch_math,3))
print("correlation of chinese and english=",np.round(corr_ch_en,3))
print()

print(np.round(np.corrcoef((chinese_score,math_score,english_score)),3))

avg= [67.167 66.6   75.333]
max= [89. 85. 90.]
min= [48. 60. 65.]
std= [13.434  9.708  8.825]

avg_math= 64.667
max_math= 85.0
min_math= 55.0
std_math= 9.86

correlation of chinese and math= 0.741
correlation of chinese and english= 0.978

[[1.    0.741 0.978]
 [0.741 1.    0.786]
 [0.978 0.786 1.   ]]


# 7 線性代數應用
array1 = np.array([[10, 8], [3, 5]]) 

運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?

運用上列array計算特徵值、特徵向量?

運用上列array計算SVD?

In [78]:
import numpy as np
import numpy.linalg as la
#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
print("#1")
array1=np.array([[10, 8], [3, 5]])
inv_array1=la.inv(array1)
mult_array1_in=np.dot(array1,inv_array1)
print('inverse of array1=')
print(inv_array1)
print()
print('mult_array1_in=')
print(mult_array1_in)
#運用上列array計算特徵值、特徵向量?
print("\n#2")
eig_val,eig_vec=la.eig(array1)
print("eigen value=",eig_val)
print("eig_vec=")
print(eig_vec)
print()
print("vector1=",eig_vec[:,0])
print("corrospond with eigen value=",eig_val[0])
#運用上列array計算SVD?
print("\n#3")
u,s,vh=la.svd(array1)
print("u=")
print(u)
print()
print("s=")
print(s)
print()
print("vh=")
print(vh)
print()

#1
inverse of array1=
[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]

mult_array1_in=
[[1. 0.]
 [0. 1.]]

#2
eigen value= [13.  2.]
eig_vec=
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]

vector1= [0.93632918 0.35112344]
corrospond with eigen value= 13.0

#3
u=
[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]

s=
[13.94721714  1.86417116]

vh=
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]



In [79]:
'''結構化陣列
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
呈上題，將array中體重(weight)數據集取出算出全部平均體重
呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重
'''
import numpy as np 
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

#1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，
# 並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
student_type = {'names':('name', 'sex', 'weight', 'rank', 'myopia'), 'formats':('U10','U6','f8','i4','?')}
students = np.zeros(8,dtype=student_type)
print(students)
students['name'] = name_list
students['sex'] = sex_list
students['weight'] = weight_list
students['rank'] = rank_list
students['myopia'] = myopia_list
print("#1")
print(students[0])
#2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
avg_weight=np.mean(students['weight'])
print("\n#2")
print(avg_weight)
#3. 呈上題，進一步算出男生(sex欄位是boy)平均體重
boy_index = np.where(students['sex']=='boy')[0]
boy_weight_avg=np.mean(students['weight'][boy_index])
print("\n#3")
print(boy_weight_avg)
#3. 呈上題，進一步算出女生(sex欄位是girl)平均體重
girl_index = np.where(students['sex']=='girl')[0]
girl_weight_avg=np.mean(students['weight'][girl_index])
print("\n#3-2")
print(girl_weight_avg)

[('', '', 0., 0, False) ('', '', 0., 0, False) ('', '', 0., 0, False)
 ('', '', 0., 0, False) ('', '', 0., 0, False) ('', '', 0., 0, False)
 ('', '', 0., 0, False) ('', '', 0., 0, False)]
#1
('小明', 'boy', 67.5, 8, True)

#2
69.8375

#3
77.18333333333332

#3-2
47.8
